version: "3"
services:
 db:
   image: mysql:latest
   container_name: evallm-db
   ports:
     - ${DB_PORT}:3306
   environment:
     - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
     - MYSQL_USER=${DB_USERNAME}
     - MYSQL_PASSWORD=${DB_PASSWORD}
     - MYSQL_DATABASE=${DB_NAME}
   volumes:
     - ./db:/var/lib/mysql